version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: hmilien/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: hmilien/udacity-restapi-user:latest
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: hmilien/udacity-restapi-feed:latest
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: hmilien/udacity-frontend:latest
